### ISSUE TITLE
Democratize ability of community members to run video calls

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/overview#150]
We use Zoom Meetings. There are some inconvenient aspects:
- Hosting these meetings involves a privileged account.
- Recording a video can be done two different ways, both of which require some steps on the hosts laptop. Uploading that video to youtube requires YouTube account access.
- The meetings can be set up in many different ways, with various features turned on and off that may or may not suit how we hope to run meetings. (eg. if one button isn't checked, then meeting can't run without "host" account, which could be inconvenient if person with host account can't join for some reason.)

It would be wonderful to use automation to allow anyone to initiate a video call on our chosen platform. Now that we have a chatbot, we can use it to facilitate this.

# Proposed workflow

1. Run this command in chat: `@halpy zoom me recorded monday @ 2:00pm ET "My Meeting Topic"`
    * this creates a single meeting for the following Monday, set to be recorded
    * leaving out the word "recorded" means no recording
    * saying just a time assumes today
2. (Optional) If recurring, you'll have to go manually into zoom interface just one time and set it up for recurring.
    * recurring events are complicated and so prob not worth automating
3. The meeting is automatically added to the Google calendar, with the location set as the meeting url
    * the meeting link is automatically passed through a landing page to warn about recording, already built and [available here](https://edgi-video-call-landing-page.herokuapp.com/)
    * could auto-create an agenda doc skeleton, and link in event description
4. Using gcal notifier, chatbot drop a message in `#general` 24 hours in advance.
    * could drop in other channels, but more complexity? Other options:
        * use `@channel` to ensure ppl see
        * drop in a special meeting channel?
5. Using gcal notifier, chatbot drop a message in `#general` 10 minutes in advance.
    * ditto as above
5. when the first person arrives in the meeting, cloud recording begins on Zoom servers.
6. When meeting ends, recording is saved.
7. Each night, **all meetings** from the day are uploaded to youtube as private (this needs consent from SC, to go forward)
8. community calls are changed to unlisted, and added to playlist.

# To Do

- [x] build landing page app
- [x] create chatbot command for ondemand calls: `@halpy zoom me now My Meeting Topic`
- [x] ~create chatbot command for pre-scheduled calls~ not critical (https://github.com/edgi-govdata-archiving/edgi-hubot/issues/13)
- [x] ~create gcal notifier~ not critical (https://github.com/edgi-govdata-archiving/edgi-hubot/issues/10)
- [x] host visual script-runner https://github.com/edgi-govdata-archiving/overview/issues/149 (in progress)
- [x] write script to upload videos to YT (half done) [EDIT: done. runs nightly] [`edgi-govdata-archiving/edgi-scripts`](https://github.com/edgi-govdata-archiving/edgi-scripts)
- [ ] add chatbot command to transfer videos zoom-to-youtube via script-runner: https://github.com/edgi-govdata-archiving/edgi-hubot/issues/26
- [x] better document `edgi-scripts` repo: https://github.com/edgi-govdata-archiving/edgi-scripts/issues/7
- [x] ~auto-create agenda/notes doc for gcal event description.~ not critical
- [x] ~make these pieces as non-edgi-specific as possible and share them with other groups :tada:~ not critical

**Comment by dcwalk** [comment]
@patcon just circling back on this -- what is the status of the todos, are there any blockers? I'm just realizing we've created a whole other area of EDGI projects that are this support infra structure and I'm not entirely sure the status of all these projects. What might be a good way to track 'em?

**Comment by dcwalk** [comment]
ping @patcon

**Comment by patcon** [comment]
thanks! updated checklist to remove non critical things. added some links to issues where the work can be tracked (that might still be worth doing in the future, just not now) :)

**Comment by dcwalk** [comment]
I'm gonna call this closed @patcon -- I think some of the checklist items might no longer fit? Please re-open if it should be
