### ISSUE TITLE
Clean up issues and setup cycle milestones for fall

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/overview#174]
Per July 10 [Archiving/Tech Working Group meeting](https://hackmd.io/MwDgRgrAJg7AnCAtANlTRAWEUCGjtzArARgDGFAZgKYBMAjDkA==#), we are going to:

- [x] clean up current issue labels in overview repo
- [x] review and close out issues that no longer reflect current projects/ways of working
- [x] add milestones to begin to experiment with tracking planning/goal cycles

In addition I'd like to
- [x] ping decision-holders when unclear about status of issue (i.e., is this `wontdo` or closable?)'
  - [x] resolve status for ~#139~ ~#150~ ~#156~ ~#130~ ~#166~ ~#143~
- [x] identify [stalled issues](https://github.com/edgi-govdata-archiving/overview/issues?q=is%3Aopen+is%3Aissue+label%3Astalled)

**Comment by dcwalk** [comment]
Hey, this might have been a noisy day for @titaniumbones and @patcon -- if so here is why!

**Comment by dcwalk** [comment]
Issues that may be resolved, potentially `wontdo` or unclear about status/next step: 
- ~#139~
- ~#150~
- ~#156~
- ~#130~ 
- #166
- #143

**Comment by dcwalk** [comment]
Hey @patcon this is the collector github issue I was talking about!

**Comment by patcon** [comment]
Do you think `stalled` label can be applied to `blocked` issues? Should there be a distinction?

**Comment by dcwalk** [comment]
Hmmmm, I think they are distinct, and don't have strong feelings either way about adding another label if that feels more descriptive!

That said the outcome (no ability to move forward) is the same, which I think is the status I'm more concerned in capturing! I'd understand that with two or one labels tho.

**Comment by dcwalk** [comment]
This has been done! The conversation around `stalled` v `blocked` can be moved to a new issue (reticketing!)
